name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - run: npm i -g @antfu/ni
      - run: corepack enable

      - uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3
        with:
          node-version: 18
          cache: pnpm


      - name: Install dependencies
        run: nci

      - name: Lint
        run: nr lint

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - run: npm i -g @antfu/ni
      - run: corepack enable

      - uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3
        with:
          node-version: 18
          cache: pnpm


      - name: Install dependencies
        run: nci

      - name: Build
        run: nr build

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - run: npm i -g @antfu/ni
      - run: corepack enable

      - uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: nci

      - name: Test
        run: nr test --no-watch --no-progress --browsers=ChromeHeadless
